#!/usr/bin/env python3
"""What one decision costs — the dimension `docs/PREFLIGHT-RESULTS.md` never measured.

That document settles the *accuracy* question: a two-term rule reproduces the
oracle on every held-out row, and the trained rungs only tie it. Ties are
supposed to resolve downward (§4), so the rule shipped.

But a tie on accuracy is not a tie. A gate runs on the critical path of a pull
request, and the two candidates are not the same shape there:

  the rule   two comparisons on values the resolver already computed
  the model  build 29 features, scale them, call `predict_proba`

This measures that difference at the shape the gate actually has — **one change
at a time**. Batch throughput is measured too, because it is the friendliest
possible framing for the model and leaving it out would be the same selective
reporting this project exists to refuse.

Timings are not byte-reproducible, so this is deliberately kept out of
`make regen-check`: a document that cannot be regenerated byte-for-byte has no
business pretending it can. Repeated runs on one machine land within a few
hundred × of each other, which is why the published claim is an order of
magnitude rather than a number.

Usage:
    make decision-cost
    scripts/measure_decision_cost.py --write     # refresh docs/DECISION-COST.md
"""

from __future__ import annotations

import argparse
import platform
import statistics
import sys
import timeit
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
DOCUMENT = ROOT / "docs" / "DECISION-COST.md"


def _median_ns(call, *, loops: int, repeat: int = 7) -> float:
    """Median of repeated timed loops.

    The loop count matters and is not a detail. The rule decides in tens of
    nanoseconds, which is *below* the cost of reading the clock twice — timing
    it one call at a time measures `perf_counter_ns`, not the rule, and the
    first version of this script did exactly that: it reported the batched
    model as faster than a rule that is two comparisons. `timeit` amortises the
    clock across many calls, which is the only way a sub-microsecond operation
    can be compared to a microsecond one at all.
    """
    samples = timeit.repeat(call, number=loops, repeat=repeat)
    return statistics.median(samples) * 1e9 / loops


def measure() -> dict[str, float | int | str]:
    import numpy
    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import StandardScaler
    from train_preflight import SEED, SchemaCache, features, load_rows, split_by_model

    rows = load_rows()
    schema = SchemaCache()
    train, test, _ = split_by_model(rows)
    keys = sorted(features(rows[0]["context"], rows[0]["diff"], schema))

    def matrix(subset: list[dict]):
        x = numpy.array(
            [
                [features(row["context"], row["diff"], schema)[key] for key in keys]
                for row in subset
            ],
            dtype=float,
        )
        y = numpy.array(
            [1 if row["verdict"] == "BLOCK" else 0 for row in subset], dtype=int
        )
        return x, y

    train_x, train_y = matrix(train)
    test_x, _ = matrix(test)

    scaler = StandardScaler().fit(train_x)
    model = LogisticRegression(max_iter=2000, random_state=SEED).fit(
        scaler.transform(train_x), train_y
    )

    # The rule, on the two values it actually reads. Both candidates are handed
    # an input that is already built, so this compares deciding — not parsing.
    vector = features(test[0]["context"], test[0]["diff"], schema)
    unknown, downstream = vector["has_unknown_referenced"], vector["downstream"]

    def rule_decision() -> int:
        return 1 if unknown or downstream else 0

    one_row = test_x[:1]

    def model_decision():
        return model.predict_proba(scaler.transform(one_row))[:, 1]

    def model_batch():
        return model.predict_proba(scaler.transform(test_x))[:, 1]

    rule_ns = _median_ns(rule_decision, loops=200_000)
    model_ns = _median_ns(model_decision, loops=200)
    batch_ns = _median_ns(model_batch, loops=5) / len(test_x)

    return {
        "machine": f"{platform.system()} {platform.machine()} · Python {platform.python_version()}",
        "test_rows": len(test_x),
        "features": len(keys),
        "rule_ns": rule_ns,
        "model_ns": model_ns,
        "model_batch_ns": batch_ns,
        "single_ratio": model_ns / rule_ns,
        "batch_ratio": batch_ns / rule_ns,
    }


def render(result: dict) -> str:
    return f"""# What one decision costs

> Measured by `scripts/measure_decision_cost.py`. Timings are not
> byte-reproducible, so this document is refreshed deliberately rather than
> guarded by `make regen-check`. The absolute figures belong to one machine and
> one run; repeated runs on this machine put the headline ratio between roughly
> 2,500× and 3,000×, so read it as three orders of magnitude, not as a constant.

`docs/PREFLIGHT-RESULTS.md` settles the accuracy question — a two-term rule
reproduces the oracle on every held-out row, and the trained rungs only tie it.
This is the dimension that document never measured, and a tie on accuracy is
not a tie once the gate is on the critical path of a pull request.

| candidate | per decision | relative |
| --- | ---: | ---: |
| the shipped two-term rule | {result["rule_ns"]:.0f} ns | 1× |
| logistic regression, one change | {result["model_ns"] / 1000:.0f} µs | **~{round(result["single_ratio"] / 100) * 100:,}× slower** |
| logistic regression, amortised over {result["test_rows"]:,} rows at once | {result["model_batch_ns"]:.0f} ns | {result["batch_ratio"]:.1f}× slower |

Measured on {result["machine"]}, median of repeated timed loops, both candidates
handed an input that is already built — so this compares deciding, not parsing.
The loop matters: the rule decides in less time than it takes to read the clock
twice, so it can only be timed in bulk.

**The middle row is the one the gate lives in.** A pull request arrives alone;
there are never 7,000 of them to vectorise. Building the {result["features"]}-feature
vector, scaling it, and crossing into `predict_proba` costs three orders of
magnitude more than the decision it produces.

The batch row is published because it is the friendliest possible framing for
the model, and omitting it would be exactly the selective reporting this project
refuses. It is also the more interesting number: even at its absolute best —
amortised over {result["test_rows"]:,} rows in one vectorised call — the model
still does not reach the rule.

So the tie in `PREFLIGHT-RESULTS.md` was only ever a tie on accuracy. Same
verdicts, and one candidate is three orders of magnitude cheaper at the shape a
gate really has. That is not why the rule shipped — §1 decided that on
determinism alone, before any of this was measured — but it is why keeping the
decision on the critical path costs nothing.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="refresh docs/DECISION-COST.md"
    )
    arguments = parser.parse_args()

    result = measure()
    print(f"machine          {result['machine']}")
    print(f"rule             {result['rule_ns'] / 1000:.4f} µs/decision")
    print(f"model (one)      {result['model_ns'] / 1000:.2f} µs/decision")
    print(f"model (batched)  {result['model_batch_ns'] / 1000:.4f} µs/decision")
    print()
    print(f"single decision: the model is {result['single_ratio']:.0f}x slower")
    print(f"batched:         the model is {result['batch_ratio']:.0f}x slower")

    if arguments.write:
        DOCUMENT.write_text(render(result), encoding="utf-8")
        print(f"\nwrote {DOCUMENT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
