#!/usr/bin/env python3
"""What one decision costs — the dimension `docs/PREFLIGHT-RESULTS.md` never measured.

That document settles the *accuracy* question: a two-term rule reproduces the
oracle on every held-out row, and the trained rungs only tie it. Ties are
supposed to resolve downward (§4), so the rule shipped.

But a tie on accuracy is not a tie. A gate runs on the critical path of a pull
request, and the two candidates are not the same shape there:

  the rule   two comparisons on values the resolver already computed
  the model  build 29 features, scale them, call `predict_proba`

This measures that difference at the shape the gate actually has — **one change
at a time**. Batch throughput is measured too, because it is the friendliest
possible framing for the model and leaving it out would be the same selective
reporting this project exists to refuse.

Timings are not byte-reproducible, so this is deliberately kept out of
`make regen-check`: a document that cannot be regenerated byte-for-byte has no
business pretending it can. Repeated runs on one machine land within a few
hundred × of each other, which is why the published claim is an order of
magnitude rather than a number.

Usage:
    make decision-cost
    scripts/measure_decision_cost.py --write     # refresh docs/DECISION-COST.md
"""

from __future__ import annotations

import argparse
import json
import math
import platform
import statistics
import sys
import timeit
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
DOCUMENT = ROOT / "docs" / "DECISION-COST.md"
# A CUDA machine is not a build dependency, so the GPU answer is measured on one
# and committed as evidence rather than regenerated here. `--export` writes the
# fitted weights for that machine; `--gpu` runs there and writes this file back.
GPU_RESULT = ROOT / "data" / "benchmark" / "decision-cost-gpu.json"


def _median_ns(call, *, loops: int, repeat: int = 7) -> float:
    """Median of repeated timed loops.

    The loop count matters and is not a detail. The rule decides in tens of
    nanoseconds, which is *below* the cost of reading the clock twice — timing
    it one call at a time measures `perf_counter_ns`, not the rule, and the
    first version of this script did exactly that: it reported the batched
    model as faster than a rule that is two comparisons. `timeit` amortises the
    clock across many calls, which is the only way a sub-microsecond operation
    can be compared to a microsecond one at all.
    """
    samples = timeit.repeat(call, number=loops, repeat=repeat)
    return statistics.median(samples) * 1e9 / loops


def measure() -> dict[str, float | int | str]:
    import numpy
    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import StandardScaler
    from train_preflight import SEED, SchemaCache, features, load_rows, split_by_model

    rows = load_rows()
    schema = SchemaCache()
    train, test, _ = split_by_model(rows)
    keys = sorted(features(rows[0]["context"], rows[0]["diff"], schema))

    def matrix(subset: list[dict]):
        x = numpy.array(
            [
                [features(row["context"], row["diff"], schema)[key] for key in keys]
                for row in subset
            ],
            dtype=float,
        )
        y = numpy.array(
            [1 if row["verdict"] == "BLOCK" else 0 for row in subset], dtype=int
        )
        return x, y

    train_x, train_y = matrix(train)
    test_x, _ = matrix(test)

    scaler = StandardScaler().fit(train_x)
    model = LogisticRegression(max_iter=2000, random_state=SEED).fit(
        scaler.transform(train_x), train_y
    )

    # The rule, on the two values it actually reads. Both candidates are handed
    # an input that is already built, so this compares deciding — not parsing.
    vector = features(test[0]["context"], test[0]["diff"], schema)
    unknown, downstream = vector["has_unknown_referenced"], vector["downstream"]

    def rule_decision() -> int:
        return 1 if unknown or downstream else 0

    one_row = test_x[:1]

    def model_decision():
        return model.predict_proba(scaler.transform(one_row))[:, 1]

    def model_batch():
        return model.predict_proba(scaler.transform(test_x))[:, 1]

    rule_ns = _median_ns(rule_decision, loops=200_000)
    model_ns = _median_ns(model_decision, loops=200)
    batch_ns = _median_ns(model_batch, loops=5) / len(test_x)

    # Stripped of scikit-learn entirely: the same scale, dot product and sigmoid
    # written by hand. This is the model's floor on a CPU — no API, no dispatch,
    # no validation — and it is what says whether the gap is arithmetic or
    # overhead. It is the number the GPU question turns on.
    weights = model.coef_[0].tolist()
    bias = float(model.intercept_[0])
    centre, spread = scaler.mean_.tolist(), scaler.scale_.tolist()
    values = test_x[0].tolist()

    def bare_arithmetic() -> float:
        total = bias
        for index, value in enumerate(values):
            total += ((value - centre[index]) / spread[index]) * weights[index]
        return 1.0 / (1.0 + math.exp(-total))

    bare_ns = _median_ns(bare_arithmetic, loops=20_000)

    return {
        "bare_ns": bare_ns,
        "bare_ratio": bare_ns / rule_ns,
        "machine": f"{platform.system()} {platform.machine()} · Python {platform.python_version()}",
        "test_rows": len(test_x),
        "features": len(keys),
        "rule_ns": rule_ns,
        "model_ns": model_ns,
        "model_batch_ns": batch_ns,
        "single_ratio": model_ns / rule_ns,
        "batch_ratio": batch_ns / rule_ns,
    }


def export(path: Path) -> None:
    """Write the fitted weights and held-out matrix for a CUDA machine to read.

    The corpus is 32 MB and deliberately uncommitted, so the GPU box cannot
    rebuild the model itself. It receives the *same fitted weights* instead —
    otherwise the two machines would be benchmarking two different models.
    """
    import numpy
    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import StandardScaler
    from train_preflight import SEED, SchemaCache, features, load_rows, split_by_model

    rows = load_rows()
    schema = SchemaCache()
    train, test, _ = split_by_model(rows)
    keys = sorted(features(rows[0]["context"], rows[0]["diff"], schema))

    def matrix(subset: list[dict]):
        return numpy.array(
            [
                [features(row["context"], row["diff"], schema)[key] for key in keys]
                for row in subset
            ],
            dtype=float,
        ), numpy.array(
            [1 if row["verdict"] == "BLOCK" else 0 for row in subset], dtype=int
        )

    train_x, train_y = matrix(train)
    test_x, _ = matrix(test)
    scaler = StandardScaler().fit(train_x)
    model = LogisticRegression(max_iter=2000, random_state=SEED).fit(
        scaler.transform(train_x), train_y
    )
    numpy.savez(
        path,
        coef=model.coef_[0],
        intercept=model.intercept_,
        mean=scaler.mean_,
        scale=scaler.scale_,
        test=test_x,
    )


def measure_gpu(path: Path) -> dict:
    """The same decision on CUDA, in four framings from honest to most generous.

    Run this on a machine with a GPU, against the file `--export` produced. The
    interesting framings are the last two: a gate never has the input already
    resident on the device, and it never has thousands of changes to decide at
    once — but both are published because a comparison that only shows the
    opponent's worst case is not a comparison.
    """
    import numpy
    import torch

    if not torch.cuda.is_available():
        raise SystemExit("no CUDA device; run this on the GPU machine")

    data = numpy.load(path)
    device = torch.device("cuda")

    def tensor(name: str):
        return torch.tensor(data[name], dtype=torch.float32, device=device)

    weights, bias = tensor("coef"), tensor("intercept")
    centre, spread = tensor("mean"), tensor("scale")
    test = data["test"]
    batch = torch.tensor(test, dtype=torch.float32, device=device)
    resident, host_row = batch[:1], test[:1].astype(numpy.float32)

    unknown, downstream = bool(test[0][0]), float(test[0][1])

    def rule() -> int:
        return 1 if unknown or downstream else 0

    def one_roundtrip() -> float:
        x = torch.from_numpy(host_row).to(device)
        # `.item()` is not incidental: it forces the device-to-host sync that
        # having a verdict actually requires. Timing without it measures how
        # fast work can be *queued*, which is not how fast a decision arrives.
        return torch.sigmoid(((x - centre) / spread) @ weights + bias).item()

    def one_resident() -> float:
        return torch.sigmoid(((resident - centre) / spread) @ weights + bias).item()

    def whole_batch():
        result = torch.sigmoid(((batch - centre) / spread) @ weights + bias)
        torch.cuda.synchronize()
        return result

    rule_ns = _median_ns(rule, loops=200_000)
    for call in (one_roundtrip, one_resident, whole_batch):
        call()  # warm up: the first CUDA call pays for context creation

    return {
        "gpu": torch.cuda.get_device_name(0),
        "torch": torch.__version__,
        "rows": len(test),
        "rule_ns": rule_ns,
        "roundtrip_ns": _median_ns(one_roundtrip, loops=500),
        "resident_ns": _median_ns(one_resident, loops=500),
        "batch_ns": _median_ns(whole_batch, loops=50) / len(test),
    }


def _gpu_section() -> str:
    if not GPU_RESULT.exists():
        return ""
    gpu = json.loads(GPU_RESULT.read_text(encoding="utf-8"))
    rule = gpu["rule_ns"]
    return f"""
## "But you measured a CPU"

The fair objection, answered by measuring rather than by arguing. Same fitted
weights, on {gpu["gpu"]} with torch {gpu["torch"]}, all four numbers from that
one machine so the ratios are against its own baseline.

| candidate, on the GPU machine | per decision | relative |
| --- | ---: | ---: |
| the shipped two-term rule | {rule:.0f} ns | 1× |
| one decision, host memory in and out | {gpu["roundtrip_ns"] / 1000:.1f} µs | **{gpu["roundtrip_ns"] / rule:,.0f}× slower** |
| one decision, input already on the device | {gpu["resident_ns"] / 1000:.1f} µs | {gpu["resident_ns"] / rule:,.0f}× slower |
| {gpu["rows"]:,} decisions in one call | {gpu["batch_ns"]:.1f} ns | **{rule / gpu["batch_ns"]:.0f}× faster** |

**A GPU makes the gate's case worse, not better, and the reason is in the CPU
numbers above**: stripped of scikit-learn entirely — the same scale, dot product
and sigmoid written out by hand — the arithmetic is a small fraction of what
`predict_proba` costs. Almost all of the gap is per-call overhead, and a GPU's
answer to overhead is to add a host-to-device round trip to it. Even with the
input already sitting on the card, which no gate receiving one pull request will
ever have, it is still three orders of magnitude behind two comparisons.

**And the last row is a real win, so it is printed in bold too.** Given
{gpu["rows"]:,} changes to decide at once, the GPU is genuinely faster per
decision than the rule — the hardware does what it is for. It just requires the
one thing a gate never has: every decision available at the same moment. A pull
request arrives alone.

None of this changes what ships, because §1 decided that on determinism before
any of it was measured. What it settles is that no hardware argument reopens the
question.
"""


def render(result: dict) -> str:
    return f"""# What one decision costs

> Measured by `scripts/measure_decision_cost.py`. Timings are not
> byte-reproducible, so this document is refreshed deliberately rather than
> guarded by `make regen-check`. The absolute figures belong to one machine and
> one run; repeated runs on this machine put the headline ratio between roughly
> 2,500× and 3,000×, so read it as three orders of magnitude, not as a constant.

`docs/PREFLIGHT-RESULTS.md` settles the accuracy question — a two-term rule
reproduces the oracle on every held-out row, and the trained rungs only tie it.
This is the dimension that document never measured, and a tie on accuracy is
not a tie once the gate is on the critical path of a pull request.

| candidate | per decision | relative |
| --- | ---: | ---: |
| the shipped two-term rule | {result["rule_ns"]:.0f} ns | 1× |
| logistic regression, one change | {result["model_ns"] / 1000:.0f} µs | **~{round(result["single_ratio"] / 100) * 100:,}× slower** |
| the same maths by hand, no framework at all | {result["bare_ns"] / 1000:.1f} µs | {result["bare_ratio"]:.0f}× slower |
| logistic regression, amortised over {result["test_rows"]:,} rows at once | {result["model_batch_ns"]:.0f} ns | {result["batch_ratio"]:.1f}× slower |

Measured on {result["machine"]}, median of repeated timed loops, both candidates
handed an input that is already built — so this compares deciding, not parsing.
The loop matters: the rule decides in less time than it takes to read the clock
twice, so it can only be timed in bulk.

**The second row is the one the gate lives in.** A pull request arrives alone;
there are never 7,000 of them to vectorise. Building the {result["features"]}-feature
vector, scaling it, and crossing into `predict_proba` costs three orders of
magnitude more than the decision it produces.

**The third row says where that cost actually is.** Written out by hand — the
same scale, dot product and sigmoid, no scikit-learn at all — the model needs
{result["bare_ns"] / 1000:.1f} µs. So the arithmetic is a small fraction of the
{result["model_ns"] / 1000:.0f} µs measured above and the rest is per-call
overhead. That matters for exactly one reason: overhead is not what faster
hardware removes.

The batch row is published because it is the friendliest possible framing for
the model, and omitting it would be exactly the selective reporting this project
refuses. It is also the more interesting number: even at its absolute best —
amortised over {result["test_rows"]:,} rows in one vectorised call — the model
still does not reach the rule.

So the tie in `PREFLIGHT-RESULTS.md` was only ever a tie on accuracy. Same
verdicts, and one candidate is three orders of magnitude cheaper at the shape a
gate really has. That is not why the rule shipped — §1 decided that on
determinism alone, before any of this was measured — but it is why keeping the
decision on the critical path costs nothing.
""" + _gpu_section()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="refresh docs/DECISION-COST.md"
    )
    parser.add_argument(
        "--export", type=Path, help="write the fitted weights for a CUDA machine"
    )
    parser.add_argument(
        "--gpu", type=Path, help="measure on CUDA, against an --export file"
    )
    arguments = parser.parse_args()

    if arguments.export:
        export(arguments.export)
        print(f"wrote {arguments.export}")
        return 0

    if arguments.gpu:
        gpu = measure_gpu(arguments.gpu)
        print(json.dumps(gpu, indent=2))
        return 0

    result = measure()
    print(f"machine          {result['machine']}")
    print(f"rule             {result['rule_ns'] / 1000:.4f} µs/decision")
    print(f"model (one)      {result['model_ns'] / 1000:.2f} µs/decision")
    print(f"model (bare)     {result['bare_ns'] / 1000:.4f} µs/decision")
    print(f"model (batched)  {result['model_batch_ns'] / 1000:.4f} µs/decision")
    print()
    print(f"single decision: the model is {result['single_ratio']:.0f}x slower")
    print(f"bare arithmetic: the model is {result['bare_ratio']:.0f}x slower")
    print(f"batched:         the model is {result['batch_ratio']:.0f}x slower")

    if arguments.write:
        DOCUMENT.write_text(render(result), encoding="utf-8")
        print(f"\nwrote {DOCUMENT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
